version: '3.5'

services:
   db:
      image: postgres:13
      restart: always
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
         POSTGRES_DB: dialdatadb
      ports:
         - 5432:5432