spring:
  application:
    name: dial-data

#  profiles:
#    include: postgres

server:
  error:
    include-message: always
  port: 9092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health

dial:
  data:
    messaging:
      security:
        signature:
          ttl: PT1M
          enabled: false # Disable until Mobile app is ready
          algorithm: EdDSA
    bitcoin:
      network: testnet # Available options: testnet, regtest, main
      localhost: false
      blockstore: memory # Available options: memory, Postgres

logging:
  level:
    root: INFO