spring:
  datasource:
#    url: jdbc:postgresql://dial-data.clg6kxm72irr.us-east-1.rds.amazonaws.com:5432/dialDB
    url: jdbc:postgresql://dial-data.clg6kxm72irr.us-east-1.rds.amazonaws.com:5432/dialDB
    username: user
    password: password
  jpa:
    hibernate:   # TODO: WILLIE Change with flyway
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

dial:
  data:
    bitcoin:
      blockstore: postgres # Available options: memory, Postgres

management:
  health:
    db:
      enabled: true
