spring:
  application:
    name: dial-data
  datasource:
    url: jdbc:postgresql://dial-data.clg6kxm72irr.us-east-1.rds.amazonaws.com:5432/dialDB
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always
  port: 9092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true

dial:
  data:
    messaging:
      security:
        signature:
          ttl: PT1M
          enabled: false # Disable until Mobile app is ready
          algorithm: EdDSA
    bitcoin:
      network: testnet # Available options: testnet, regtest, main
      localhost: false

logging:
  level:
    root: INFO
