spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dialdatadb
    username: user
    password: password
  jpa:
    hibernate:   # TODO: WILLIE Change with flyway
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

dial:
  data:
    bitcoin:
      blockstore: postgres # Available options: memory, Postgres

management:
  health:
    db:
      enabled: true
